# Change these first
owner: nikolai-cc
repo: upp

sites:
  - name: nikolai.cc
    url: https://www.nikolai.cc
  - name: altijd design
    url: https://www.altijd.design
  - name: theministry
    url: https://www.theministry.co
  - name: Massasjehuset
    url: https://www.massasjehuset.nl
  - name: Rob Alofs
    url: http://www.robalofs.nl
  - name: Betsinor
    url: https://www.betsinor.fr
  - name: LEDbits
    url: https://www.ledbits.eu
  - name: Bumi Bars
    url: https://www.bumibars.nl


status-website:
  baseUrl: /upp
  logoUrl: https://raw.githubusercontent.com/nikolai-cc/upp/master/assets/sadcomputer.jpg
  name: Upptime
  theme: ocean
  introTitle: "**nikolai-cc**"
  introMessage: "Some sites."
  metaTags:
    - name: "robots"
      content: "noindex"
  navbar:
    - title: Go away
      href: https://nikolai.cc
